# Generated by Django 3.1.6 on 2021-02-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
